//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENLAIHOANTRAPHONG
    {
        public int IDBL { get; set; }
        public int IDSINHVIEN { get; set; }
        public int IDHOCKI { get; set; }
        public string NGAYTRAPHONG { get; set; }
        public decimal TIENHOANTRA { get; set; }
        public string NGUOITHUNGAN { get; set; }
        public string TENSINHVIEN { get; set; }
    
        public virtual HOCKI HOCKI { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
