//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHSV_PHONG
    {
        public int IDSINHVIEN { get; set; }
        public int IDPHONG { get; set; }
        public string NGAYVAO { get; set; }
        public string NGAYRA { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
