//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKTXEntities3 : DbContext
    {
        public QLKTXEntities3()
            : base("name=QLKTXEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIENLAIHOANTRAPHONG> BIENLAIHOANTRAPHONGs { get; set; }
        public virtual DbSet<BIENLAITHUEPHONG> BIENLAITHUEPHONGs { get; set; }
        public virtual DbSet<BIENLAITIENPHONG> BIENLAITIENPHONGs { get; set; }
        public virtual DbSet<CANBO> CANBOes { get; set; }
        public virtual DbSet<DANHSACHSV_PHONG> DANHSACHSV_PHONG { get; set; }
        public virtual DbSet<DANHSACHSV_TIENPHONG> DANHSACHSV_TIENPHONG { get; set; }
        public virtual DbSet<GIADIEN> GIADIENs { get; set; }
        public virtual DbSet<GIANUOC> GIANUOCs { get; set; }
        public virtual DbSet<HOCKI> HOCKIs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIENDIENNUOC> TIENDIENNUOCs { get; set; }
        public virtual DbSet<TIENTHUEPHONG> TIENTHUEPHONGs { get; set; }
        public virtual DbSet<TOA> TOAs { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
