//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.BIENLAITHUEPHONGs = new HashSet<BIENLAITHUEPHONG>();
            this.BIENLAITIENPHONGs = new HashSet<BIENLAITIENPHONG>();
            this.DANHSACHSV_PHONG = new HashSet<DANHSACHSV_PHONG>();
            this.DANHSACHSV_TIENPHONG = new HashSet<DANHSACHSV_TIENPHONG>();
            this.TIENDIENNUOCs = new HashSet<TIENDIENNUOC>();
        }
    
        public string TENPHONG { get; set; }
        public int IDTOA { get; set; }
        public Nullable<int> SOLUONGNGUOI { get; set; }
        public Nullable<int> LOAIPHONG { get; set; }
        public Nullable<int> SOLUONGTRONG { get; set; }
        public int IDPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAITHUEPHONG> BIENLAITHUEPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAITIENPHONG> BIENLAITIENPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHSV_PHONG> DANHSACHSV_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHSV_TIENPHONG> DANHSACHSV_TIENPHONG { get; set; }
        public virtual TIENTHUEPHONG TIENTHUEPHONG { get; set; }
        public virtual TOA TOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIENDIENNUOC> TIENDIENNUOCs { get; set; }
    }
}
