//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOA()
        {
            this.PHONGs = new HashSet<PHONG>();
        }
    
        public string TENTOA { get; set; }
        public string SOLUONGPHONG { get; set; }
        public Nullable<bool> TOANAM { get; set; }
        public Nullable<int> TSGIUONGTRONG { get; set; }
        public Nullable<int> TSGIUONG { get; set; }
        public Nullable<int> TONGDATHUE { get; set; }
        public int IDTOA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG> PHONGs { get; set; }
    }
}
