//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENLAITIENPHONG
    {
        public int IDBL { get; set; }
        public Nullable<int> IDSINHVIEN { get; set; }
        public Nullable<int> ID_DSSV_TIENPHONG { get; set; }
        public Nullable<int> IDHOCKI { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public string NGAYINBL { get; set; }
        public string TENNGUOITHU { get; set; }
        public Nullable<bool> DONGTIENPHONG { get; set; }
        public Nullable<bool> DONGTIENBHYT { get; set; }
        public Nullable<bool> DONGTIENBHTN { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> TIENPHONGDADONG { get; set; }
    
        public virtual DANHSACHSV_TIENPHONG DANHSACHSV_TIENPHONG { get; set; }
        public virtual HOCKI HOCKI { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
