//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENLAITHUEPHONG
    {
        public int IDVL { get; set; }
        public Nullable<int> IDSINHVIEN { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string TENNHAPHONG { get; set; }
        public Nullable<int> LOAIPHONG { get; set; }
        public Nullable<bool> DADONGTIENPHONG { get; set; }
        public Nullable<int> IDHOCKI { get; set; }
        public string TENHOCKI { get; set; }
        public string NGAYVAO { get; set; }
        public string NGAYTRAPHONG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOCKI HOCKI { get; set; }
        public virtual PHONG PHONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
