//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.BIENLAIHOANTRAPHONGs = new HashSet<BIENLAIHOANTRAPHONG>();
            this.BIENLAITHUEPHONGs = new HashSet<BIENLAITHUEPHONG>();
            this.BIENLAITIENPHONGs = new HashSet<BIENLAITIENPHONG>();
            this.DANHSACHSV_PHONG = new HashSet<DANHSACHSV_PHONG>();
            this.DANHSACHSV_TIENPHONG = new HashSet<DANHSACHSV_TIENPHONG>();
        }
    
        public string NGAYSINH { get; set; }
        public string HOTEN { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string MSSV { get; set; }
        public string TENTRUONG { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public string QUOCTICH { get; set; }
        public string DANTOC { get; set; }
        public string NGAYVAOKTX { get; set; }
        public string NGAYRAKTX { get; set; }
        public string SINHVIENNAM { get; set; }
        public string KHOA { get; set; }
        public Nullable<bool> DATHUE { get; set; }
        public int IDSINHVIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAIHOANTRAPHONG> BIENLAIHOANTRAPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAITHUEPHONG> BIENLAITHUEPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENLAITIENPHONG> BIENLAITIENPHONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHSV_PHONG> DANHSACHSV_PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHSV_TIENPHONG> DANHSACHSV_TIENPHONG { get; set; }
    }
}
