//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomitoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDIENNUOC
    {
        public int IDPHONG { get; set; }
        public System.DateTime THOIGIAN { get; set; }
        public int CHISODIEN { get; set; }
        public int CHISONUOC { get; set; }
        public decimal THANHTIEN { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public string NGAYTHU { get; set; }
        public int IDBL { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
